import { useState } from 'react'
import { AdminLayout } from '../components/layout/AdminLayout'
import { KitchenOverview } from '../components/staff/KitchenOverview'
import { RecentActivityPanel } from '../components/staff/RecentActivityPanel'
import { StaffMap } from '../components/staff/StaffMap'
import { StaffPageHeader } from '../components/staff/StaffPageHeader'
import { StaffPerformancePanel } from '../components/staff/StaffPerformancePanel'
import { StaffSummaryCards } from '../components/staff/StaffSummaryCards'
import { StaffTabs, type StaffTab } from '../components/staff/StaffTabs'
import { WaiterCard } from '../components/staff/WaiterCard'
import { WorkloadPanel } from '../components/staff/WorkloadPanel'
import { kitchenStaff, otherStaff, waiters } from '../data/mockStaffData'
import type { StaffMember } from '../types/staff'
export function StaffPage(){const[tab,setTab]=useState<StaffTab>('waiters');const[selected,setSelected]=useState('juan');const visible:StaffMember[]=tab==='kitchen'?kitchenStaff:tab==='other'?otherStaff:tab==='all'?[...waiters,...otherStaff]:waiters;return <AdminLayout><StaffPageHeader/><StaffSummaryCards/><StaffTabs active={tab} onChange={setTab}/><div className="staff-layout"><div className="staff-main"><section className="waiters-section"><header><span>EQUIPO DE SALÓN</span><h2>{tab==='kitchen'?'COCINA':tab==='other'?'BARMAN / OTROS':tab==='all'?'TODO EL PERSONAL':'MESEROS EN SERVICIO (8)'}</h2></header><div className="waiters-grid">{visible.map(staff=><WaiterCard key={staff.id} staff={staff} selected={selected===staff.id} onSelect={member=>setSelected(member.id)}/>)}</div></section><KitchenOverview/><StaffMap/></div><aside className="staff-rail"><WorkloadPanel/><StaffPerformancePanel/><RecentActivityPanel/></aside></div></AdminLayout>}
